var challenge = '30 Days Of JavaScript'
console.log(challenge)
console.log(challenge.length)
console.log(challenge.toUpperCase())
console.log(challenge.toLowerCase())
console.log(challenge.substr(0,1))
console.log(challenge.substring(0,1))
console.log(challenge.substring(3, challenge.length))
console.log(challenge.includes('Script'))
console.log(challenge.split())
console.log(challenge.split(' '))
var str1 = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon'
console.log(str1.split(','))
console.log(challenge.replace('JavaScript' , 'Python'))
console.log(challenge.charAt(15))
console.log(challenge.charCodeAt('J'))
console.log(challenge.indexOf('a'))
console.log(challenge.lastIndexOf('a'))
var str2 = 'You cannot end a sentence with because because because is a conjunction'
console.log(str2.indexOf('because'))
console.log(str2.lastIndexOf('because'))
console.log(str2.search('because'))
console.log(str2.trim(' '))
console.log(str2.startsWith('3'))
console.log(str2.endsWith('t'))
console.log(str2.match('a'))
var str3 = ''
console.log(str3.concat('30DaysOf','JavaScript'))
console.log(str2.repeat(2))